name = "QueryOperators"
uuid = "2aef5ad7-51ca-5a8f-8e88-e75cf067b44b"
version = "0.9.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
TableShowUtils = "5e66a065-1f0a-5976-b372-e0b8c017ca10"

[compat]
DataStructures = "≥ 0.11.0"
DataValues = "≥ 0.4.4"
IteratorInterfaceExtensions = "^0.1.1, ^1"
TableShowUtils = "≥ 0.1.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
